test:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV["POSTGRES_DB"]%>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  username: <%= ENV['POSTGRES_USER'] %>
