send_recap_emails:
  # cron: "0 15 * * *" # At 15:00 every day
  cron: "*/30 * * * * *" # Execute every 30 seconds for testing purposes
  class: "SendRecapEmails"
  queue: default
  args:
    hour: 15 # This should be in sync with the "cron" time